### ISSUE TITLE
Flaky CI on MacOS

### ISSUE THREAD

**Issue by rlamy** [iterative/pytest-servers#142]
CI runs on MacOS are failing intermittently, due to timeouts in setting up fake_gcs_server or azurite. This is annoying in downstream projects testing on MacOS, as it causes spurious failures as well

**Comment by dtrifiro** [comment]
It's on my radar. I think it's related to poor performance of MacOS runners with colima, currently checking if increasing timeout helps https://github.com/iterative/pytest-servers/pull/141

**Comment by jonburdo** [comment]
Should we consider making that container setup timeout configurable so the user can adjust it?

**Comment by dtrifiro** [comment]
By further investigation, it seems that the containers are up and well, but the port forwarding to the colima vm fails, resulting in the container published ports not being exposed on the MacOS host. I reported some of my findings [here](https://github.com/abiosoft/colima/issues/962).

A (terrible 😭) workaround is to run `colima restart` when the published ports are not exposed on the host @rlamy

**Comment by shcheklein** [comment]
I think it's resolved for now, by using the previous stable version.
