### ISSUE TITLE
run moto s3 in docker ?

### ISSUE THREAD

**Issue by dtrifiro** [iterative/pytest-servers#16]
We currently run `moto` in a subprocess. It might be worth it to run it in a docker container as we do for azurite (see #13)

**Comment by efiop** [comment]
@skshetry We are running a pre-installed command anyway, just easier with docker.

**Comment by skshetry** [comment]
> @skshetry We are running a pre-installed command anyway, just easier with docker.
> 
> Though with moto maybe we can nicely run the server too. But for the rest (e.g. azurite) easier to manage in docker. Though could also run locally, but random-port selection will be problematic.

Are there any benefits to running in docker?

**Comment by efiop** [comment]
@skshetry Ease of installation - `docker run` and you are done without messing with manually installing different servers from different locations (e.g. moto on pypi, but azurite on npm, which is a pain to install and more servers like that in the future). With docker we don't have to pollute your environment installing all these and won't have to worry about any coflicts or inconsistencies (e.g. you happened to install some boto version that doesn't work with this moto server or installed a newer moto version that doesn't work with our suit, etc).

Also all docker fixtures are already in dvc and dvc-* plugins, so you just need to copy it into place and you are done.

**Comment by skshetry** [comment]
I'm talking only about `moto`. It is installed by default when you do `pip install pytest-servers` and should work out of the box, more so than the docker. `pip` should handle any conflicts regarding versions. Inconsistency or issues with boto is rare.

**Comment by efiop** [comment]
@skshetry Docker seems cleaner to me (though more heavy weight), but I'm fine with using moto server directly if we can make sure we are not polluting hardcoded ports.

**Comment by efiop** [comment]
Btw, speaking about isolation and polution. Might be related https://github.com/iterative/dvc-data/runs/7156375557?check_suite_focus=true

**Comment by dtrifiro** [comment]
I agree with @skshetry here. It's easy to run `moto` without bothering with docker. In https://github.com/iterative/pytest-servers/pull/18 I made it so that moto uses a random port, addressing the hardcoded ports issue

**Comment by dtrifiro** [comment]
I'll close this for now since #18 has been merged. We can re-evaluate in the future if we need more isolation with docker.
