### ISSUE TITLE
tmp_upath_factory: could it be more simpler?

### ISSUE THREAD

**Issue by skshetry** [iterative/pytest-servers#25]
We have factories for other filesystems based upath as:
1. `tmp_upath_factory.local_temp_path(...)`
2. `tmp_upath_factory.s3_temp_path(..)`
3. ...

Could it be more simpler without redundant `temp_path` prefix? eg:
1. `tmp_upath_factory.local(...)`
2. `tmp_upath_factory.s3(...)`
3. ...

I guess the arguments against my suggestion could be:
1. that this will be confusing with `tmp_upath_factory.mktemp("s3")`, etc.
2. or, that it breaks symmetry with individual fixtures: `local_path`, `s3_path`, etc.
    (how about `tmp_upath_factory.local_path(...)` then? I'd still cut `path` though).

**Comment by dtrifiro** [comment]
I agree, the  `temp_path` suffix is redundant.

I'm not sure what you think would be confusing about point 1. About point 2, I don't think it really matters.

How about something like `make_local`, `make_s3`, `make_gcs` and `make_azure`, which could perhaps even be shortened to `mklocal`, `mks3`, etc? After all, all of these are used `mktemp`.
